CREATE TABLE `video` (
                         `aid` bigint(20) NOT NULL COMMENT '视频aid',
                         `videos` int(11) NOT NULL COMMENT '视频分P总数，默认为1',
                         `tid` int(11) NOT NULL COMMENT '分区tid',
                         `tname` varchar(255) DEFAULT NULL COMMENT '子分区名称',
                         `copyright` int(11) NOT NULL,
                         `pic` varchar(255) DEFAULT NULL COMMENT '视频封面图片url',
                         `title` varchar(255) DEFAULT NULL COMMENT '视频标题',
                         `pubdate` bigint(20) NOT NULL COMMENT '稿件发布时间',
                         `ctime` bigint(20) NOT NULL,
                         `desc` text COMMENT '视频的简介',
                         `state` int(11) NOT NULL,
                         `duration` int(11) NOT NULL COMMENT '视频总计持续时长（所有分P）',
                         `owner` varchar(255) DEFAULT NULL COMMENT 'json存储 Owner对象',
                         `dynamic` varchar(255) DEFAULT NULL,
                         `cid` bigint(20) NOT NULL COMMENT '视频1P cid',
                         `short_link_v2` varchar(255) DEFAULT NULL COMMENT 'bv号短链接',
                         `up_from_v2` int(11) NOT NULL,
                         `first_frame` varchar(255) DEFAULT NULL,
                         `pub_location` varchar(255) DEFAULT NULL,
                         `favorite` tinyint(1) NOT NULL COMMENT '是否已收藏',
                         `type` int(11) NOT NULL COMMENT '视频属性 3普通视频 4剧集 5课程',
                         `sub_type` int(11) NOT NULL COMMENT '附视频属性',
                         `device` int(11) NOT NULL COMMENT '观看平台代码',
                         `page` varchar(2550) DEFAULT NULL COMMENT 'json存储 Page对象',
                         `count` int(11) NOT NULL COMMENT '分P数',
                         `progress` int(11) NOT NULL COMMENT '观看进度',
                         `view_at` bigint(20) NOT NULL COMMENT '观看时间',
                         `kid` bigint(20) NOT NULL COMMENT '稿件avid',
                         `business` varchar(255) DEFAULT NULL,
                         `redirect_link` varchar(255) DEFAULT NULL COMMENT '重定向url',
                         `bvid` varchar(255) DEFAULT NULL COMMENT '稿件bvid',
                         PRIMARY KEY (`aid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='视频表';